### ISSUE TITLE
Rotation of robot can't go further then 360 degrees

### ISSUE THREAD

**Issue by kwint** [ros-gopigo/gopigo3_node#3]
Hi, 

When rotating the robot more then 360 degrees the TF message doesn't go futher then 360 or 0 degrees. I think it should be that the rotation should reset to 0 when the robot rotation get higher then 360, and the other way around.

See this video: https://streamable.com/7kfog

I tried to solving this error myself but no luck so far.

(Could it be that this is how TF works?!)

**Comment by christianrauch** [comment]
The problem is maybe in:
```
old_angle = 2*np.arccos(self.pose.pose.orientation.w)
new_angle = old_angle+angle
new_q = quaternion_about_axis(new_angle, (0, 0, 1))
```
The `old_angle` is by `arccos` only defined in [0, 2pi] and when the small change in `angle` is added, it gets maybe rounded back to [0, 2pi] in `quaternion_about_axis` instead of wrapping the angle around.

Can you check that `new_angle` is really limited to [0, 2pi] and that it is not only the quaternion `new_q` that stays constant?

**Comment by kwint** [comment]
I won't be able to test until next Thursday, will test it then

**Comment by kwint** [comment]
Seems that New Angle is sort of limited by [0, 2pi]. It does get a bit lower than 0 and a bit higher than 2pi, but then gets "corrected". 
See values here: https://gist.github.com/kwint/d0dff13918e6fa4007f1689ac883502e

**Comment by kwint** [comment]
Found a fix. old_angle will be saved in the gopigo object

**Comment by christianrauch** [comment]
Thanks for looking into this. Storing the angle in degree is definitely a solution to this issue.
However, I am wondering why the conversion over quaternion does cause this issue.

Converting the quaternion to angle via `np.arccos`, limits the angle to [0,2pi] for qw=[-1,+1] but `quaternion_about_axis` (https://github.com/ros/geometry/blob/4ee2cff7b2ec0b4e72928b5b476cd074eb974fc3/tf/src/tf/transformations.py#L1157-L1171) should wrap around 2pi when converting the new angle back to quaternion (i.e. in `quaternion[3] = math.cos(angle/2.0)`).

I guess we need to manually apply wrapping around of `new_angle` (e.g. using modulo like in https://stackoverflow.com/a/15927914/8144672) before converting it back to quaternion.

**Comment by christianrauch** [comment]
I wrapped the angle in range 0..2pi, this seems to fix the issue.
Can you check branch [`fix_orientation`](https://github.com/ros-gopigo/gopigo3_node/tree/fix_orientation) if it solves your issue?

**Comment by kwint** [comment]
Unfortunately the project that I did with the gopigo has ended, so I don't have access to the robot anymore.

**Comment by christianrauch** [comment]
The fix is now in `master`.
