### ISSUE TITLE
missing package nav_msgs

### ISSUE THREAD

**Issue by TCIII** [ros-gopigo/gopigo3_node#6]
After following the instructions to install the GoPiGo3Node, I attempted to run the “Test your installation” commands and received this error message:

```
File “/home/pi/gopigo3_ws/src/src/gopigo3_driver.py”, line 21, in 
from nav_msgs.msg import Odometry
ImportError: No module named nav_msgs.msg
```

Did I somehow error during the GoPiGo3Node installation since there appears to be a missing package named nav_msgs.msg and how can this be corrected?

Additionally, during catkin_make, these error messages appeared which I think has something to do with the above error message:

```
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
Could not find a package configuration file provided by “nav_msgs” with any
of the following names:

nav_msgsConfig.cmake
nav_msgs-config.cmake
Add the installation prefix of “nav_msgs” to CMAKE_PREFIX_PATH or set
“nav_msgs_DIR” to a directory containing one of the above files. If
“nav_msgs” provides a separate development package or SDK, be sure it has
been installed.
Call Stack (most recent call first):
CMakeLists.txt:10 (find_package)

– Configuring incomplete, errors occurred!
See also “/home/pi/gopigo3_ws/build/CMakeFiles/CMakeOutput.log”.
See also “/home/pi/gopigo3_ws/build/CMakeFiles/CMakeError.log”.(upload://cPfkRY8IuGNVgXq1I2Nb8czfqQz.txt) (1.1 KB)

Invoking “cmake” failed
```

[CMakeError.txt](https://github.com/ros-gopigo/gopigo3_node/files/3571696/CMakeError.txt)

**Comment by christianrauch** [comment]
Yes, you are missing the [`nav_msgs`](http://wiki.ros.org/nav_msgs) package.

If you are using a binary ROS distribution via package manager, you should be able to automatically install the dependencies by running `rosdep install --from-paths src --ignore-src -y` from the workspace. You can also install the specific `nav_msgs` dependency via  `sudo apt install ros-melodic-nav-msgs`. For source distributions, you can clone the package (https://github.com/ros/common_msgs.git) into the same workspace.

**Comment by TCIII** [comment]
Hi Christian,

Thanks for the response, much appreciated.

I installed ROS Kentic using these instructions: http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Kinetic%20on%20the%20Raspberry%20Pi

Will your "sudo apt install ros-melodic-nav-msgs" work with Kinetic?

I am new to ROS and the GoPiGoNode installation process and was using these instructions: https://medium.com/robotics-with-ros/starting-with-ros-on-the-gopigo3-and-the-raspberry-pi-af62104d401e

Comments?

**Comment by christianrauch** [comment]
The binary ROS package in the apt repositories typically have the name scheme `ros-<distro>-<package>`. The package `ros-melodic-nav-msgs` is the package for ROS `melodic`. For ROS kinetic, you will have to install `ros-kinetic-nav-msgs`.

In any case, `rosdep install --from-paths src --ignore-src -y` should automatically determine and install the correct package. I also update the wiki (https://github.com/ros-gopigo/gopigo3_node/wiki) accordingly.

**Comment by TCIII** [comment]
Thanks for the update, much appreciated.

**Comment by christianrauch** [comment]
Did `rosdep` work for you to install the dependencies? Are you able to run the `gopigo3_driver` node?

**Comment by TCIII** [comment]
I will try it today. I live in FL and we have been under a Tropical Storm watch, but have not lost power.

**Comment by TCIII** [comment]
After running `rosdep install --from-paths src --ignore-src -y` I received this CLI message:

```
pi@dex:~/gopigo3_ws/src $ rosdep install --from-paths src --ignore-src -y
#All required rosdeps installed successfully
```

However, CMake is still failing:

```
pi@dex:~/gopigo3_ws $ catkin_make
Base path: /home/pi/gopigo3_ws
Source space: /home/pi/gopigo3_ws/src
Build space: /home/pi/gopigo3_ws/build
Devel space: /home/pi/gopigo3_ws/devel
Install space: /home/pi/gopigo3_ws/install
####
#### Running command: "cmake /home/pi/gopigo3_ws/src -DCATKIN_DEVEL_PREFIX=/home/pi/gopigo3_ws/devel -DCMAKE_INSTALL_PREFIX=/home/pi/gopigo3_ws/install -G Unix Makefiles" in "/home/pi/gopigo3_ws/build"
####
-- Using CATKIN_DEVEL_PREFIX: /home/pi/gopigo3_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/pi/gopigo3_ws/devel;/opt/ros/kinetic
-- This workspace overlays: /home/pi/gopigo3_ws/devel;/opt/ros/kinetic
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/pi/gopigo3_ws/build/test_results
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.18
-- BUILD_SHARED_LIBS is on
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "nav_msgs" with any
  of the following names:

    nav_msgsConfig.cmake
    nav_msgs-config.cmake

  Add the installation prefix of "nav_msgs" to CMAKE_PREFIX_PATH or set
  "nav_msgs_DIR" to a directory containing one of the above files.  If
  "nav_msgs" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)


-- Could not find the required component 'nav_msgs'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "nav_msgs" with any
  of the following names:

    nav_msgsConfig.cmake
    nav_msgs-config.cmake

  Add the installation prefix of "nav_msgs" to CMAKE_PREFIX_PATH or set
  "nav_msgs_DIR" to a directory containing one of the above files.  If
  "nav_msgs" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/pi/gopigo3_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/gopigo3_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
```

Since I am new at Linux programming, am I doing something wrong?

**Comment by christianrauch** [comment]
No, that looks correct. I have no idea why it doesn't install the `nav_msgs` dependency.

You will have to install the package manually as described above. Either via the binary package `ros-kinetic-nav-msgs` or by cloning the source package to the workspace.

**Comment by TCIII** [comment]
Thanks for the update.

My next step was going to be starting over by cloning the source package to the workspace assuming that it has been updated as you indicated above.

What would be the commands to do do a binary package install using ros-kinetic-nav-msgs?

I am a beginner and need examples to learn.

**Comment by christianrauch** [comment]
Try `sudo apt install ros-kinetic-nav-msgs`.

**Comment by TCIII** [comment]
I tried this from the root directory:
```
pi@dex:~ $ sudo apt install ros-kinetic-nav-msgs
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ros-kinetic-nav-msgs
```

Should I be in this directory: 
```
pi@dex:~/gopigo3_ws $ sudo apt install ros-kinetic-nav-msgs
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ros-kinetic-nav-msgs
```

Tried this from the workspace:
```
pi@dex:~/gopigo3_ws $ rosdep install --from-paths src --ignore-src -y
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
gopigo3_node: No definition of [tf] for OS [debian]
```

I get this when trying to clone the source package to the workspace:
```
pi@dex:~ $ git clone https://github.com/ros-gopigo/gopigo3_node.git
fatal: destination path 'gopigo3_node' already exists and is not an empty directory.
```

How do I get around that issue?

Thanks for all your help, much appreciated. Learning a lot here.

**Comment by christianrauch** [comment]
Clarification:
It does not matter from where you call `sudo apt install`. It operates independently from your current working directory. But `rosdep install` has to be called from the workspace (in your case `gopigo3_ws`). It will search your packages for rosdep keys like `nav_msgs` or `tf` and try to install corresponding packages.

Did you install ROS from source or from a binary distribution? If you are using a binary distribution, the package `ros-kinetic-nav-msgs` should be available.

I assume that the package `gopigo3_node` is already part of your workspace. So you do not need (and also shouldn't) clone it again. Can you follow the instructions at https://github.com/ros-gopigo/gopigo3_node/wiki/Installation to make sure that you clone the ROS nodes into the right paths? The source for ROS nodes is typically located in a subfolder `src` within your workspace. You also need to make sure that you source the workspace (`source devel/setup.bash`) in order for catkin to find all other ROS packages in the main workspace in `/opt/ros/kinetic`.

If in doubt, remove all the folders you created and repeat the steps in the wiki to create and compile the workspace from scratch.

**Comment by TCIII** [comment]
Yes, gopigo3_node is already a part of my workspace.

Your link to the gopigo2_node installation instructions differ from these: https://medium.com/robotics-with-ros/starting-with-ros-on-the-gopigo3-and-the-raspberry-pi-af62104d401e

I found the instructions from your link once before, but couldn't find them again.

I assume that I can use "'m <file>': Deletes a file. For a folder add option -rf (recursive and force)" to delete files in the gopigo3_node directory and the gopigo3_ws directory? I assume that the gopigo3_node and gopigo3_ws are folders (directory)?

Example: to remove gopigo3_node Folder: "rm -rf /gopigo3_node"
By the way, Folder gopigo3_node is empty

Also "rm -rf/gopigo3_ws" which contains build, devel, and src 

Both gopigo3_node and gopigo3_ws are sub folders in the root folder (directory)

**Comment by TCIII** [comment]
I think I see the problem: The instructions that I used https://medium.com/robotics-with-ros/starting-with-ros-on-the-gopigo3-and-the-raspberry-pi-af62104d401e does not include the command string: "source /opt/ros/kinetic/setup.bash". Should this command string be executed at the root level and then follow the rest of instructions in your link after I remove the gopigo3_node and gopigo3_ws Folders (Directories?

Also the flow of the instructions that I used are somewhat different from the link that you have provided.

I assume that I can use "'rm <file>': Deletes a file. For a folder add option -rf (recursive and force)"
to remove the gopigo3_ws and gopigo3_node Folders which are sub folders in the root directory?  The Gopigo3_ws Folder contains build, devel, and src while the gopigo3_node Folder is empty.

Example: "rm -rf /gopigo3_ws" and "rm -rf/gopigo3_node"

**Comment by christianrauch** [comment]
The instructions from the medium article are slightly outdated. They are based on the wiki page (that I included in the previous posts).

Indeed, the article does not mention `source /opt/ros/kinetic/setup.bash` explicitly. But this is part of the documentation (http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Kinetic%20on%20the%20Raspberry%20Pi) on installing ROS kinetic, that you forwarded. Section 3.3 mentions `echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc`. This will add the sourcing command to the bashrc. The next time you log in, the main ROS kinetic workspace will be sourced automatically.
Before compiling a new workspace, you need to have the main workspace sourced because it most likely contains the dependencies that you need. This can be done automatically by adding it to the bashrc file, as shown in the documentation, or you manually need to call `source /opt/ros/kinetic/setup.bash`. You can do this from anywhere; it does not need to be from the workspace you are compiling.

Yes, the command `rm -rf` will remove a folder and all its content irreversible.

**Comment by TCIII** [comment]
Hi Christian,

Using sudo rm -rf /gopigo3_ws and sudo rm -rf /gopigo3_node does not remove these Folders (directories) from the root directory so I can try and reinstall the GoPiGo3_Node.

Comments?

**Comment by slowrunner** [comment]
> Example: "rm -rf /gopigo3_ws" and "rm -rf/gopigo3_node"

@TCIII wrong path:  
```
(cd ~    which is /home/pi)
rm -rf gopigo3_ws
rm -rf gopigo3_node
```
should work (the reason rm or rmdir alone didn't work was probably because of a .git file)

BUT now that you understand that, (and shouldn't need to do it) - you should have success using the [procedure at the end of issue 7](https://github.com/ros-gopigo/gopigo3_node/issues/7#issuecomment-528412326) to add the missing ROS packages.  You can DM me on the DI forum if you want.

**Comment by TCIII** [comment]
Hi Christian,

Thanks for the update and support, much appreciated.

Please see the following DI GoPiGo3 ROS GoPiGo3 Node Build Thread as to what I have accomplished. Almost there, but there is still a problem when running "Test The Installation" commands.

https://forum.dexterindustries.com/t/ros-gopigo3-node-build-success/6840

**Comment by TCIII** [comment]
All the issues associated with this software have been resolved.
