### ISSUE TITLE
Ok to ask a question here? What is the Servo mentioned in the gopigo3_driver.py

### ISSUE THREAD

**Issue by pitosalas** [ros-gopigo/gopigo3_node#9]
I dont know if you prefer me to ask questions somewhere else?

Thanks!

**Comment by christianrauch** [comment]
I don't mind for now if there are not too many questions. But generally, the issue section should be reserved for problems with the ROS node. Maybe you can ask such questions in the [Dexter Industries Forum](https://forum.dexterindustries.com).

Anyway, the servo refers to the servo in the [Servo Package](https://shop.dexterindustries.com/servo-package). You can set the server position/angle by a position or pulse-width value.

**Comment by pitosalas** [comment]
Thanks. Do you respond to questions in the forum, because I’m happy to ask there of course.

Pito Salas
Brandeis Computer Science
Volen 134

**Comment by christianrauch** [comment]
No, I haven't used the GoPiGo3 for a long time now. But I think there are others that use the ROS node and questions about the usage of the extern devices can also be asked at the forum. The ROS node is mostly just a thin wrapper around the python library. Most questions about interacting with sensors or actuators directly relate to the usage of the python library.
